modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/CreativeCore/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="creativecore"
    logoFile="creativecore.png"
    version="2.11.22"
    displayName="CreativeCore"
    displayURL="https://modrinth.com/mod/creativecore"
    authors="CreativeMD"
    description='''A simple but powerful coremod.'''

[[dependencies.creativecore]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativecore]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
   config="creativecore.mixins.json"

[[mixins]]
   config="creativecore.forge.mixins.json"

